<a href="https://colab.research.google.com/github/mostlydipo/AI-Data-science/blob/main/nba_rookie_data_GNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # Data processing(files)
import numpy as np # Mathematics computation
import matplotlib.pyplot as plt # Plots and graphs

In [ ]:
# Sklearn library for machine learning
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

In [ ]:
nba=pd.read_csv('nba_rookie_data.csv') # Extract data.
nba.head() # First 5 rows of the data.

,Name,Games Played,Minutes Played,Points Per Game,Field Goals Made,Field Goal Attempts,Field Goal Percent,3 Point Made,3 Point Attempt,3 Point Percent,...,Free Throw Attempts,Free Throw Percent,Offensive Rebounds,Defensive Rebounds,Rebounds,Assists,Steals,Blocks,Turnovers,TARGET_5Yrs
0,Brandon Ingram,36,27.4,7.4,2.6,7.6,34.7,0.5,2.1,25.0,...,2.3,69.9,0.7,3.4,4.1,1.9,0.4,0.4,1.3,0
1,Andrew Harrison,35,26.9,7.2,2.0,6.7,29.6,0.7,2.8,23.5,...,3.4,76.5,0.5,2.0,2.4,3.7,1.1,0.5,1.6,0
2,JaKarr Sampson,74,15.3,5.2,2.0,4.7,42.2,0.4,1.7,24.4,...,1.3,67.0,0.5,1.7,2.2,1.0,0.5,0.3,1.0,0
3,Malik Sealy,58,11.6,5.7,2.3,5.5,42.6,0.1,0.5,22.6,...,1.3,68.9,1.0,0.9,1.9,0.8,0.6,0.1,1.0,1
4,Matt Geiger,48,11.5,4.5,1.6,3.0,52.4,0.0,0.1,0.0,...,1.9,67.4,1.0,1.5,2.5,0.3,0.3,0.4,0.8,1

**Data cleaning(Remove errorneous values)**

In [ ]:
nba.isnull().any().any() # Check for null values.

True

In [ ]:
nba.columns[nba.isna().any()] # Check the column where null values exists

Index(['3 Point Percent'], dtype='object')

In [ ]:
nba.dropna(inplace= True) # Drop null values.

In [ ]:
nba.isna().any() # check if null value has been dropped

Name                   False
Games Played           False
Minutes Played         False
Points Per Game        False
Field Goals Made       False
Field Goal Attempts    False
Field Goal Percent     False
3 Point Made           False
3 Point Attempt        False
3 Point Percent        False
Free Throw Made        False
Free Throw Attempts    False
Free Throw Percent     False
Offensive Rebounds     False
Defensive Rebounds     False
Rebounds               False
Assists                False
Steals                 False
Blocks                 False
Turnovers              False
TARGET_5Yrs            False
dtype: bool

In [ ]:
nb = nba.drop('Name', axis=1) # Drop name column.
nb

,Games Played,Minutes Played,Points Per Game,Field Goals Made,Field Goal Attempts,Field Goal Percent,3 Point Made,3 Point Attempt,3 Point Percent,Free Throw Made,Free Throw Attempts,Free Throw Percent,Offensive Rebounds,Defensive Rebounds,Rebounds,Assists,Steals,Blocks,Turnovers,TARGET_5Yrs
0,36,27.4,7.4,2.6,7.6,34.7,0.5,2.1,25.0,1.6,2.3,69.9,0.7,3.4,4.1,1.9,0.4,0.4,1.3,0
1,35,26.9,7.2,2.0,6.7,29.6,0.7,2.8,23.5,2.6,3.4,76.5,0.5,2.0,2.4,3.7,1.1,0.5,1.6,0
2,74,15.3,5.2,2.0,4.7,42.2,0.4,1.7,24.4,0.9,1.3,67.0,0.5,1.7,2.2,1.0,0.5,0.3,1.0,0
3,58,11.6,5.7,2.3,5.5,42.6,0.1,0.5,22.6,0.9,1.3,68.9,1.0,0.9,1.9,0.8,0.6,0.1,1.0,1
4,48,11.5,4.5,1.6,3.0,52.4,0.0,0.1,0.0,1.3,1.9,67.4,1.0,1.5,2.5,0.3,0.3,0.4,0.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,80,15.8,4.3,1.6,3.6,43.3,0.0,0.2,14.3,1.2,1.5,79.2,0.4,0.8,1.2,2.5,0.6,0.2,0.8,0
1336,68,12.6,3.9,1.5,4.1,35.8,0.1,0.7,16.7,0.8,1.0,79.4,0.4,1.1,1.5,2.3,0.8,0.0,1.3,1
1337,43,12.1,5.4,2.2,3.9,55.0,0.0,0.0,0.0,1.0,1.6,64.3,1.5,2.3,3.8,0.3,0.3,0.4,0.9,0
1338,52,12.0,4.5,1.7,3.8,43.9,0.0,0.2,10.0,1.2,1.8,62.5,0.2,0.4,0.7,2.2,0.4,0.1,0.8,1
1339,47,11.7,4.4,1.6,4.4,36.9,0.4,1.3,33.3,0.7,1.0,67.3,0.2,0.7,0.9,1.4,0.7,0.1,0.9,1

**Data wrangling(Scaling and structruting of data)**

In [ ]:
scaler = MinMaxScaler() # Transforms numeric feature data to range 0 to 1.
 
nbs = scaler.fit_transform(nb.to_numpy())
nbs = pd.DataFrame(nbs, columns=[
    'Games Played',	'Minutes Played',	'Points Per Game',	'Field Goals Made',	'Field Goal Attempts',	'Field Goal Percent',	'3 Point Made',	'3 Point Attempt'	,'3 Point Percent',
    'Free Throw Made',	'Free Throw Attempts',	'Free Throw Percent',	'Offensive Rebounds',	'Defensive Rebounds',	'Rebounds',	'Assists',	'Steals', 'Blocks',	'Turnovers',	'TARGET_5Yrs'])
 
print("Scaled Dataset Using MinMaxScaler")
nbs.head()

Scaled Dataset Using MinMaxScaler

,Games Played,Minutes Played,Points Per Game,Field Goals Made,Field Goal Attempts,Field Goal Percent,3 Point Made,3 Point Attempt,3 Point Percent,Free Throw Made,Free Throw Attempts,Free Throw Percent,Offensive Rebounds,Defensive Rebounds,Rebounds,Assists,Steals,Blocks,Turnovers,TARGET_5Yrs
0,0.352113,0.642857,0.243636,0.232323,0.357895,0.218437,0.217391,0.323077,0.250,0.207792,0.225490,0.699,0.132075,0.340426,0.279412,0.179245,0.16,0.102564,0.279070,0.0
1,0.338028,0.629630,0.236364,0.171717,0.310526,0.116232,0.304348,0.430769,0.235,0.337662,0.333333,0.765,0.094340,0.191489,0.154412,0.349057,0.44,0.128205,0.348837,0.0
2,0.887324,0.322751,0.163636,0.171717,0.205263,0.368737,0.173913,0.261538,0.244,0.116883,0.127451,0.670,0.094340,0.159574,0.139706,0.094340,0.20,0.076923,0.209302,0.0
3,0.661972,0.224868,0.181818,0.202020,0.247368,0.376754,0.043478,0.076923,0.226,0.116883,0.127451,0.689,0.188679,0.074468,0.117647,0.075472,0.24,0.025641,0.209302,1.0
4,0.521127,0.222222,0.138182,0.131313,0.115789,0.573146,0.000000,0.015385,0.000,0.168831,0.186275,0.674,0.188679,0.138298,0.161765,0.028302,0.12,0.102564,0.162791,1.0

In [ ]:
inputs= nbs.drop('TARGET_5Yrs', axis='columns') # Dependent variables.
target= nbs.TARGET_5Yrs # Indepenent variable.

In [ ]:
X_train, X_test,y_train,y_test= train_test_split(inputs,target, test_size=1/3, random_state=0) # Train, test and split data.

In [ ]:
len(X_train) # Number of traing data

886

In [ ]:
len(X_test) # Number of testing data

443

In [ ]:
len(inputs) # Total number of data

1329

**Naive Bayes models(Probalistic machine learning algorithm).**

In [ ]:
X_test[:5]

,Games Played,Minutes Played,Points Per Game,Field Goals Made,Field Goal Attempts,Field Goal Percent,3 Point Made,3 Point Attempt,3 Point Percent,Free Throw Made,Free Throw Attempts,Free Throw Percent,Offensive Rebounds,Defensive Rebounds,Rebounds,Assists,Steals,Blocks,Turnovers
1287,0.788732,0.190476,0.083636,0.080808,0.094737,0.398798,0.000000,0.000000,0.000,0.090909,0.107843,0.613,0.207547,0.170213,0.191176,0.075472,0.12,0.128205,0.162791
445,0.971831,0.452381,0.160000,0.171717,0.189474,0.448898,0.000000,0.000000,0.000,0.129870,0.137255,0.690,0.283019,0.265957,0.279412,0.094340,0.16,0.153846,0.372093
458,0.943662,0.349206,0.163636,0.191919,0.247368,0.332665,0.043478,0.030769,0.368,0.077922,0.088235,0.696,0.264151,0.202128,0.235294,0.141509,0.28,0.076923,0.255814
251,0.957746,0.470899,0.261818,0.303030,0.331579,0.450902,0.043478,0.046154,0.174,0.168831,0.215686,0.576,0.283019,0.223404,0.257353,0.198113,0.44,0.179487,0.372093
1251,0.422535,0.171958,0.123636,0.090909,0.121053,0.300601,0.086957,0.092308,0.360,0.181818,0.205882,0.682,0.094340,0.074468,0.080882,0.037736,0.12,0.102564,0.139535

In [ ]:
gnb=GaussianNB() # 66 percent accurate on a player lasting 5 years in the NBA.
gnb.fit(X_train,y_train)
print(gnb)

gnb.score(X_test,y_test)

GaussianNB()

0.6613995485327314

In [ ]:
y_test[:5]

1287    1.0
445     1.0
458     1.0
251     1.0
1251    0.0
Name: TARGET_5Yrs, dtype: float64

In [ ]:
gnb.predict(X_test[:5]) # Our GaussianNB got 2 predictions wrong(1287,458) from our y_test above. consider we have 66 percent accuracy.

array([0., 1., 0., 1., 0.])

In [ ]:
bernnb = BernoulliNB(binarize = 0.1) # Best  Naive Bayes probalistic model on a player lasting 5 years in the NBA.
bernnb.fit(X_train, y_train)
print(bernnb)

bernnb.score(X_test, y_test)

BernoulliNB(binarize=0.1)

0.6817155756207675

In [ ]:
y_test[:5]

1287    1.0
445     1.0
458     1.0
251     1.0
1251    0.0
Name: TARGET_5Yrs, dtype: float64

In [ ]:
bernnb.predict(X_test[:5]) # The BernoulliNB got 1 prediction wrong(1287) from our y_test. Consider we have 68 percent accuracy

array([0., 1., 1., 1., 0.])